## ******************************************************************************
## This source code is licensed under the MIT license found in the
## LICENSE file in the root directory of this source tree.
## ******************************************************************************

name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        We sincerely appreciate your contribution to the `astra-sim/astra-network-analytical` project. Please use this form to report a potential bug in the project you find out.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please explain to us what exactly has happened.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Project Version
      description: If possible, let us know the project version or commit ID you are currently working on.
  - type: dropdown
    id: operatingsystem
    attributes:
      label: Operating System
      description: "From which operating system have you observed this bug?"
      options:
        - Linux - Debian-based (e.g., Ubuntu) 
        - Linux - Other Distributions
        - macOS
        - Windows - Subsystem for Linux
        - Others
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce the bug
      description: Please explain to us how to reproduce the bug, e.g., which file or line to change, or how to run the program.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If possible, please provide us with any relevant program output.
      render: shell
  - type: textarea
    id: misc
    attributes:
      label: Miscellaneous
      description: Please provide us with any other relevant information you find necessary.
  - type: markdown
    attributes:
      value: |
        Thanks again for your time filling in this form.
